#ifndef WINDOW_H
#define WINDOW_H

#include <memory>

#include <GL3W/gl3w.h>
#include <GLFW/glfw3.h>

#include <ImGui/imgui.h>
#include <ImGui/imgui_impl_glfw.h>
#include <ImGui/imgui_impl_opengl3.h>

#include <core/renderer/renderer.h>

namespace GUI
{
    class GLFWWindowManager
    {
    public:
        GLFWWindowManager();
        ~GLFWWindowManager();
        void Run();                                                 // Start the GLFW window loop

    private:
        void Update();                                              // Update a new frame
        void Startup();                                             // Initialize the resources before the loop
        void UpdateController();                                    // Render the controller of the render pipeline                       
        void UpdateFramebuffer();                                   // Render the final framebuffer generated by our pipeline

    private:
        GLFWwindow* window;                                         // GLFWWindow Instance
        std::unique_ptr<Core::Renderer::Renderer> renderer;         // Renderer

    private:
        int render_mode;                                            // Renderer option
    };
}


#endif  // WINDOW_H